---
title: "New York Times API Assignment"
author: "Desiree Thomas, Kiera Griffiths, Denise Atherley"
format: html
editor: visual
---

##Approach

For this assignment, we created a New York Times Developer account in order to access their APIs. We chose to use the New York Times Article Search API, as it would allow us to filter queries. One of our data analysis questions for this dataset is this: "How has the frequency and prominence of articles regarding 'Artificial Intelligence' shifted compared to 'Data Science' over the last five years?" We aim to determine whether 'Data Science' as term is being consumed the 'Artificial Intelligence' as a term, especially considering that many times models, LLM's, etc. are 'shoved' under the broader AI marketing term. We will also examine the different sections reporting on these two terms: Technology, Business, Science.

To answer these questions, we are going to ensure that we do not expose our API key first and foremost. It will be going into a .Renviron file (and stored in the .gitignore). Next, we will use the httr2 recommended workflow (since httr is deprecated); there will be a base request and appending of the query parameters. In the API documentation it notes that the API only returns 10 articles at a time, so we will have to use purrr::map most likely. It has a rate limit that ideally should not present much of a problem for this assignment. Our data transformation will include flattening the JSON using jsonlite before we use dplyr. A tibble is deemed sufficient for this assignment so that it the minimum product we will aim to achieve.

Potential challenges: There is a 1,000 result cap which means that if the search for 'Artificial Intelligence' exceeds more than a 1,000 hits we will need to reconsider our approach strategy.
